### ISSUE TITLE
How to label cells for mapping

### ISSUE THREAD

**Issue by LisaSikkema** [hernet/transcriptional-map-nk#1]
Hi! 

I'm trying out mapping some data to your atlas (really exciting work!) and have a question about the labels the model expects: based on the model.pt file, it seems like you guys didn't include an "unlabeled" category in the cell type labels, and labeled all cells during training.
How did you deal with this when mapping new data? Did you label all the query data, and if so: how? In the paper methods I read that you used either original annotations or CellTypist. Which CellTypist model did you use, and did you use these annotations out of the box? (Couldn't find any code for it in your repo)

Thanks!

**Comment by hernet** [comment]
Hi!

Thank you for your interest in our work! Regarding the labels the models expect it varies a bit between the different models. For the PB-NK model we have the NK cell subsets as the labels and there should be an unlabeled category. We have used this model to annotate NK cell subsets in other data sets. For the models for the different tumor/tissue types it varies a bit, but mostly we have used annotations from the original data set as seed labels and trained a scANVI model in order to annotate all the cells. For all tissue/tumor types we have then taken all the immune cells and annotated these using CellTypist (v1). Mostly we've been interested in extracting the two main NK cell subsets (CD56bright and CD56dim) from these data sets, and from our experience the CD16- and CD16+ annotations that CellTypist gives us corresponds to these subsets and we have simply called these CD56bright and CD56dim.  
When it comes to what we refer to as our reference model (PB-NK and normal tissue NK) we don't include cell type/subset labels in the model. We train a scVI model, but we have the annotations of subsets from the previous analysis (the PB-NK subset analysis and the analysis of the individual tissue types). This model is the model that we use for mapping of the tumor-NK cells (query data). So the query data in that case has been annotated as described (CellTypist, but renamed as bright/dim). 
I hope this clarifies things a bit, might need to update the code to better describe these steps. I pushed a very small update to github/zenodo now, but will try to make this clearer. Let me know if there are still things that are unclear. 
Thank you!

**Comment by LisaSikkema** [comment]
Hi Herman, 
thanks a lot for the quick response, very clarifying!
So I was aiming to work with your reference model, and downloaded the "pb_tissue_normal_ref_scvi.zip" from Zenodo. Is that indeed the reference model?

When I try to map without setting any cell type labels I get an error though, asking me to set the labels:
`KeyError: 'label not found in adata.obs.'`
and it seems like the labels consisted of the following during training:
```
'Adaptive', 'CD56bright', 'CD56bright lung_normal',
'CD56bright pancreas_normal', 'CD56bright prostate_normal',
'CD56dim brain_normal', 'CD56dim breast_normal',
'CD56dim lung_normal', 'CD56dim pancreas_normal',
'CD56dim prostate_normal', 'CD57+', 'KIR+', 'NKG2A+',
```
Which made me think it was a scANVI model, but I guess it wasn't then... Not sure why it still has the requirement to set a label for the query in that case. I tried mapping a dataset without label (basically adding a new label "unknown") and the results didn't look good, I was guessing that was because I gave the cells a new cell type label as far as scANVI understood, but now I'm not sure anymore.

**Comment by hernet** [comment]
Hi
I think I see what the problem is. I think the wrong model was uploaded to zenodo initially, sorry about that. In the new version I uploaded yesterday it should be correct. And yes, the reference model should be pb_tissue_normal_ref_scvi and it can be loaded with the reference_nk.h5ad. Let me know if it still doesn't work and I'll look into it again. Thank you!

**Comment by LisaSikkema** [comment]
okay nice I'll give it another try now with the new model!
And the reference file `reference_nk.h5ad` isn't on Zenodo, I'm guessing this is `all_nk_cells.h5ad`, then subsetted to the reference?

**Comment by LisaSikkema** [comment]
oh no it's on there now, was still on the old Zenodo page, sorry!

**Comment by LisaSikkema** [comment]
Okay it's still asking for a 'label' column in my query adata.obs, but this time the mapping looks way better! I guess the problem was not in the labels :) thanks a lot for updating the new model + ref.
Also don't forget to update the Zenodo link in your readme! It's now linking to your old page (v1) instead of the new one (v2).

**Comment by hernet** [comment]
Good to hear, updated the link. Thank you :)
